from django.utils.translation import ugettext_lazy as _

HOME_META_DESCRIPTION = "Votre Plateforme de publication en ligne"
HOME_META_KEYWORDS = "flished"
HOME_PAGE_TITLE = "FLISHED"
HOME_PAGE_BANNER = _('Stories')
UI_BLOG_HOME_PAGE_TITLE = _("Publications")
UI_POST_RECENTS_TITLE = _("Recents")
UI_POST_RECOMMENDATIONS_TITLE = _("Recommendations for you")
UI_NO_RECOMMENDATIONS_TITLE = _("No Recommendations")
UI_BEST_PICK_TITLE = _("Selection of the day")
UI_SITE_CONDITIONS = _("Terms of use")
UI_PRIVACY_POLICY = _("Privacy")
UI_ABOUT_US = _('About us')
UI_FAQ = _('FAQ')
UI_FOOTER_MENTION = _('Publication Plateform')
UI_TERMS_OF_USE = 'Conditions'
UI_ABOUT_HEAD = _('Share experiences and ideas with others to build a better world')
UI_ABOUT_INTRO = _("FLISHED a free digital publishing platform. \
FLISHED is not a journalism site, it's much more than that. \
Experts are strongly encouraged to share their experiences so that as many people as possible can take advantage of it")
UI_ABOUT_BODY = _("There is no organization behind FLISHED. \
Everyone is free to write publications in the fields of their choice. \
Although FLISHED is a platform where everyone expresses themselves freely, each of us should respect others")
UI_ABOUT_CLOSING = _("Let's share our experiences for a better world")
UI_FEED_TITLE = _("FLISHED - A place where people share their experiences")
UI_FEED_DESCRIPTION = UI_ABOUT_CLOSING
UI_FEED_LATEST = _("Recents publications")
UI_FEED_RSS_VALIDATE = _("Validate our RSS feed")
UI_NO_SEARCH_RESULT_TITLE = _('No article found')
UI_NO_SEARCH_RESULT = _('Your research has no results')
UI_SEARCH_LABEL = _('Search')
UI_SEARCHED_TERM_LABEL = _('Your search term')
UI_SEARCH_RESULTS_LABEL = _('Search results for')
UI_BACK_BTN_LABEL = _('Back')
UI_CREATE_BTN_LABEL = _('Create')
UI_UPDATE_BTN_LABEL = _('Update')
UI_CANCEL_BTN_LABEL = _('Cancel')
UI_RESET_BTN_LABEL = _('Reset')
UI_CLOSE_BTN_LABEL = _('Close')
UI_SEND_BTN_LABEL = _('Send')
UI_SAVE_BTN_LABEL = _('Save')
UI_PUBLISH_BTN_LABEL = _('Publish')
UI_CONTACT_LABEL = _('Contact us')
UI_CLEAR_BTN_LABEL = _('Clear')
UI_BLOG_HOME_LABEL = _('Stories')
UI_STANDARD_POST_LIST_TITLE = _('Publications')
UI_NEW_BLOG_POST = _('New Post')
UI_POST_DELETED_MESSAGE = _('The publication has been deleted by its author.')
UI_POST_REPLY = _('Reply')
UI_POST_LIKE = _('Like')
UI_POST_UNLIKE = _('Unlike')
UI_UPDATE_BLOG_POST = _('Edit Post')
UI_DELETE_BLOG_POST = _('Delete')
UI_HOME_EMPTY_CONTENT = _('There is no publication. Be the first to publish a new one.')
UI_POST_PUBLISHED_LABEL = _('Your story has been published')
UI_POST_TITLE_MISSING_MESSAGE = _("The publication's title is missing")
UI_POST_CONTENT_MISSING_MESSAGE = _("The publication's content is empty")
UI_OPEN_POST_LINK_LABEL = _('Open your story')
UI_NO_BLOG_POSTS_HINT = _("There no posts currently. Feel free to create a new one")
UI_INVALID_USER_REQUEST = _('Invalid user request')
UI_RESOURCE_NOT_FOUND_TITLE = _('Resource not found !')
UI_RESOURCE_NOT_FOUND = _('The resource you requested does not exist or is no longer available. Visit our blog to discover other blos posts.')
UI_DISCOVER_OUR_BLOG = _('Discover our Blog')
UI_BLOG_POST_PREVIEW = _('Post Preview')
UI_BLOG_INPUT_TITLE_PLACEHOLDER = _("Story's title ...")
UI_NOT_FOUND = _('Not found')
UI_WHATSAPP_SHARE_BODY = _("Hey, have a look on this article {POST_URL}. I think it is interesting, Thanks !")

UI_EDITOR_PLACEHOLDER = _("Start typing here ...")
UI_QUOTE_PLACEHOLDER = _('Enter a quote')
UI_CAPTION_PLACEHOLDER = _('Quote\'s author')
UI_EDITOR_FIRST_COMMENT_HINT = _("Be the first to comment")
UI_POST_NEW_COMMENT_PLACEHOLDER = _("Post a comment")
UI_COMMENT_LOGIN_REQUIRED_HINT = _("Only members can comment. Please log in or create an account to comment")
UI_COMMENT_LABEL = _("Comment")
UI_COMMENT_LIST_LABEL = _("Comments")
UI_ACCOUNT_LABEL = _("Account")
UI_DASHBOARD_LABEL = _("Dashboard")

DASHBOARD_POSTS_TITLE = _('Posts')
DASHBOARD_POST_TITLE = _('Post')
DASHBOARD_POST_UPDATE_TITLE = _('Post Update')
DASHBOARD_POST_CREATE_TITLE = _('New Post')

DASHBOARD_DASHBOARD_TITLE = _('Dashboard')
DASHBOARD_COUPONS_TITLE                 = _('Coupons')
DASHBOARD_COUPON_TITLE                  = _('Coupon')
DASHBOARD_COUPON_CREATE_TITLE           = _('New Coupon')
DASHBOARD_COUPON_UPDATE_TITLE           = _('Coupon Update')

DASHBOARD_INFOS_TITLE                 = _('Infos')
DASHBOARD_INFO_TITLE                  = _('Info')
DASHBOARD_INFO_CREATE_TITLE           = _('New Info')
DASHBOARD_INFO_UPDATE_TITLE           = _('Info Update')

DASHBOARD_GROUPS_TITLE                 = _('Groups')
DASHBOARD_GROUP_TITLE                  = _('Group')
DASHBOARD_GROUP_CREATE_TITLE           = _('New Group')
DASHBOARD_GROUP_UPDATE_TITLE           = _('Group Update')


DASHBOARD_HIGHLIGHTS_TITLE                  = _('Highlights')
DASHBOARD_HIGHLIGHT_TITLE                 = _('Highlight')
DASHBOARD_HIGHLIGHT_UPDATE_TITLE           = _('Highlight Update')
DASHBOARD_HIGHLIGHT_CREATE_TITLE           = _('New Highlight')
DASHBOARD_USERS_TITLE = _('Users')
DASHBOARD_CUSTOMERS_TITLE = _('Customers')
DASHBOARD_SELLERS_TITLE = _('Sellers')
DASHBOARD_USER_TITLE = _('User')
DASHBOARD_USER_UPDATE_TITLE = _('User Update')
DASHBOARD_USER_CREATE_TITLE = _('New User')


DASHBOARD_TOKENS_TITLE = _('Tokens')
DASHBOARD_PARTNER_TOKENS_TITLE = _('Partner Tokens')
DASHBOARD_TOKEN_CREATE_TITLE = _('New Token')
DASHBOARD_SUBSCRIPTION_PAYMENT_TITLE = _('Subscription Payment')
DASHBOARD_SUBSCRIPTION_PAYMENTS_TITLE = _('Subscription Payments')
DASHBOARD_SUBSCRIPTION__CREATE_PAYMENT_TITLE = _('Create Subscription Payment')

UI_STRINGS_CONTEXT = {
    'UI_FEED_RSS_VALIDATE': UI_FEED_RSS_VALIDATE,
    'UI_FEED_LATEST': UI_FEED_LATEST,
    'UI_FEED_TITLE': UI_FEED_TITLE,
    'UI_FEED_DESCRIPTION': UI_FEED_DESCRIPTION,
    'UI_ABOUT_HEAD': UI_ABOUT_HEAD,
    'UI_ABOUT_INTRO' : UI_ABOUT_INTRO,
    'UI_ABOUT_BODY': UI_ABOUT_BODY,
    'UI_ABOUT_CLOSING': UI_ABOUT_CLOSING,
    'UI_POST_DELETED_MESSAGE': UI_POST_DELETED_MESSAGE,
    'UI_STANDARD_POST_LIST_TITLE': UI_STANDARD_POST_LIST_TITLE,
    'UI_NO_RECOMMENDATIONS_TITLE': UI_NO_RECOMMENDATIONS_TITLE,
    'UI_POST_RECOMMENDATIONS_TITLE': UI_POST_RECOMMENDATIONS_TITLE,
    'UI_BEST_PICK_TITLE': UI_BEST_PICK_TITLE,
    'UI_POST_TITLE_MISSING_MESSAGE': UI_POST_TITLE_MISSING_MESSAGE,
    'UI_POST_CONTENT_MISSING_MESSAGE': UI_POST_CONTENT_MISSING_MESSAGE,
    'UI_HOME_EMPTY_CONTENT': UI_HOME_EMPTY_CONTENT,
    'UI_DELETE_BLOG_POST': UI_DELETE_BLOG_POST,
    'UI_POST_REPLY': UI_POST_REPLY,
    'UI_POST_LIKE': UI_POST_LIKE,
    'UI_POST_UNLIKE': UI_POST_UNLIKE,
    'UI_CAPTION_PLACEHOLDER': UI_CAPTION_PLACEHOLDER,
    'UI_QUOTE_PLACEHOLDER': UI_QUOTE_PLACEHOLDER,
    'UI_EDITOR_PLACEHOLDER': UI_EDITOR_PLACEHOLDER,
    'UI_POST_PUBLISHED_LABEL': UI_POST_PUBLISHED_LABEL,
    'UI_OPEN_POST_LINK_LABEL': UI_OPEN_POST_LINK_LABEL,
    'UI_COMMENT_LABEL': UI_COMMENT_LABEL,
    'UI_COMMENT_LIST_LABEL': UI_COMMENT_LIST_LABEL,
    'UI_ACCOUNT_LABEL': UI_ACCOUNT_LABEL,
    'HOME_PAGE_BANNER': HOME_PAGE_BANNER,
    'UI_DASHBOARD_LABEL': UI_DASHBOARD_LABEL,
    'UI_POST_NEW_COMMENT_PLACEHOLDER': UI_POST_NEW_COMMENT_PLACEHOLDER,
    'UI_COMMENT_LOGIN_REQUIRED_HINT': UI_COMMENT_LOGIN_REQUIRED_HINT,
    'UI_EDITOR_FIRST_COMMENT_HINT': UI_EDITOR_FIRST_COMMENT_HINT,
    'UI_EDITOR_PLACEHOLDER': UI_EDITOR_PLACEHOLDER,
    'UI_NOT_FOUND': UI_NOT_FOUND,
    'UI_BLOG_INPUT_TITLE_PLACEHOLDER': UI_BLOG_INPUT_TITLE_PLACEHOLDER,
    'UI_BLOG_POST_PREVIEW': UI_BLOG_POST_PREVIEW,
    'UI_INVALID_USER_REQUEST': UI_INVALID_USER_REQUEST,
    'UI_RESOURCE_NOT_FOUND_TITLE': UI_RESOURCE_NOT_FOUND_TITLE,
    'UI_RESOURCE_NOT_FOUND': UI_RESOURCE_NOT_FOUND,
    'UI_DISCOVER_OUR_BLOG': UI_DISCOVER_OUR_BLOG,
    'HOME_PAGE_TITLE': HOME_PAGE_TITLE,
    'HOME_META_DESCRIPTION': HOME_META_DESCRIPTION,
    'HOME_META_KEYWORDS': HOME_META_KEYWORDS,
    'UI_PRIVACY_POLICY': UI_PRIVACY_POLICY,
    'UI_ABOUT_US': UI_ABOUT_US,
    'UI_FAQ': UI_FAQ,
    'UI_FOOTER_MENTION': UI_FOOTER_MENTION,
    'UI_TERMS_OF_USE': UI_TERMS_OF_USE,
    'UI_BACK_BTN_LABEL': UI_BACK_BTN_LABEL,
    'UI_CREATE_BTN_LABEL' : UI_CREATE_BTN_LABEL,
    'UI_UPDATE_BTN_LABEL': UI_UPDATE_BTN_LABEL,
    'UI_CANCEL_BTN_LABEL': UI_CANCEL_BTN_LABEL,
    'UI_RESET_BTN_LABEL': UI_RESET_BTN_LABEL,
    'UI_SEND_BTN_LABEL': UI_SEND_BTN_LABEL,
    'UI_CONTACT_LABEL': UI_CONTACT_LABEL,
    'UI_NO_SEARCH_RESULT_TITLE' : UI_NO_SEARCH_RESULT_TITLE,
    'UI_NO_SEARCH_RESULT': UI_NO_SEARCH_RESULT,
    'UI_SEARCH_LABEL': UI_SEARCH_LABEL,
    'UI_SEARCHED_TERM_LABEL': UI_SEARCHED_TERM_LABEL,
    'UI_SEARCH_RESULTS_LABEL': UI_SEARCH_RESULTS_LABEL,
    'UI_CLEAR_BTN_LABEL': UI_CLEAR_BTN_LABEL,
    'UI_CLOSE_BTN_LABEL': UI_CLOSE_BTN_LABEL,
    'UI_SAVE_BTN_LABEL': UI_SAVE_BTN_LABEL,
    'UI_PUBLISH_BTN_LABEL': UI_PUBLISH_BTN_LABEL,
    'UI_BLOG_HOME_LABEL': UI_BLOG_HOME_LABEL,
    'UI_NEW_BLOG_POST': UI_NEW_BLOG_POST,
    'UI_UPDATE_BLOG_POST': UI_UPDATE_BLOG_POST,
    'UI_NO_BLOG_POSTS_HINT': UI_NO_BLOG_POSTS_HINT,


}