from django.utils.translation import ugettext_lazy as _

HOME_META_DESCRIPTION = "Votre Blog actuel"
HOME_META_KEYWORDS = "jasiri"
HOME_PAGE_TITLE = "JASIRI Blog"
UI_SITE_CONDITIONS = "Protection de données & Conditions"
UI_PRIVACY_POLICY = 'Vie privée'
UI_ABOUT_US = 'A propos'
UI_FAQ = 'FAQ'
UI_FOOTER_MENTION = 'JASIRI BLOG'
UI_TERMS_OF_USE = 'Conditions'
UI_NO_SEARCH_RESULT_TITLE = _('No article found')
UI_NO_SEARCH_RESULT = _('Your research has no results')
UI_SEARCH_LABEL = _('Search')
UI_SEARCHED_TERM_LABEL = _('Your search term')
UI_SEARCH_RESULTS_LABEL = _('Search results for')
UI_BACK_BTN_LABEL = _('Back')
UI_CREATE_BTN_LABEL = _('Create')
UI_UPDATE_BTN_LABEL = _('Update')
UI_CANCEL_BTN_LABEL = _('Cancel')
UI_RESET_BTN_LABEL = _('Reset')
UI_CLOSE_BTN_LABEL = _('Close')
UI_SEND_BTN_LABEL = _('Send')
UI_SAVE_BTN_LABEL = _('Save')
UI_PLUBISH_BTN_LABEL = _('Publish')
UI_CONTACT_LABEL = _('Contact us')
UI_CLEAR_BTN_LABEL = _('Clear')


UI_STRINGS_CONTEXT = {
    'HOME_PAGE_TITLE': HOME_PAGE_TITLE,
    'HOME_META_DESCRIPTION': HOME_META_DESCRIPTION,
    'HOME_META_KEYWORDS': HOME_META_KEYWORDS,
    'UI_PRIVACY_POLICY': UI_PRIVACY_POLICY,
    'UI_ABOUT_US': UI_ABOUT_US,
    'UI_FAQ': UI_FAQ,
    'UI_FOOTER_MENTION': UI_FOOTER_MENTION,
    'UI_TERMS_OF_USE': UI_TERMS_OF_USE,
    'UI_BACK_BTN_LABEL': UI_BACK_BTN_LABEL,
    'UI_CREATE_BTN_LABEL' : UI_CREATE_BTN_LABEL,
    'UI_UPDATE_BTN_LABEL': UI_UPDATE_BTN_LABEL,
    'UI_CANCEL_BTN_LABEL': UI_CANCEL_BTN_LABEL,
    'UI_RESET_BTN_LABEL': UI_RESET_BTN_LABEL,
    'UI_SEND_BTN_LABEL': UI_SEND_BTN_LABEL,
    'UI_CONTACT_LABEL': UI_CONTACT_LABEL,
    'UI_NO_SEARCH_RESULT_TITLE' : UI_NO_SEARCH_RESULT_TITLE,
    'UI_NO_SEARCH_RESULT': UI_NO_SEARCH_RESULT,
    'UI_SEARCH_LABEL': UI_SEARCH_LABEL,
    'UI_SEARCHED_TERM_LABEL': UI_SEARCHED_TERM_LABEL,
    'UI_SEARCH_RESULTS_LABEL': UI_SEARCH_RESULTS_LABEL,
    'UI_CLEAR_BTN_LABEL': UI_CLEAR_BTN_LABEL,
    'UI_CLOSE_BTN_LABEL': UI_CLOSE_BTN_LABEL,
    'UI_SAVE_BTN_LABEL': UI_SAVE_BTN_LABEL,
    'UI_PLUBISH_BTN_LABEL': UI_PLUBISH_BTN_LABEL,

}